export const TIP_MANILA_COURSES = [
  'Architecture',
  'BA English Language',
  'BA Political Science',
  'BS Accountancy',
  'BS Accounting Information System',
  'BS Business Administration - Financial Management',
  'BS Business Administration - Human Resource Management',
  'BS Business Administration - Logistics and Supply Chain Management',
  'BS Business Administration - Marketing Management',
  'BS Chemical Engineering',
  'BS Civil Engineering',
  'BS Computer Engineering',
  'BS Computer Science',
  'BS Data Science and Analytics',
  'BS Electrical Engineering',
  'BS Electronics Engineering',
  'BS Entertainment and Multimedia Computing - Digital Animation Technology',
  'BS Entertainment and Multimedia Computing - Game Development',
  'BS Industrial Engineering',
  'BS Information Systems',
  'BS Information Technology',
  'BS Mechanical Engineering',
  'Senior High School - ABM',
  'Senior High School - HUMSS',
  'Senior High School - STEM',
]

export const YEAR_LEVELS = [1, 2, 3, 4, 5, 6]
