import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import BackLink from '../../components/BackLink.jsx'
import { supabase } from '../../services/supabase/client.js'
const blank={student_number:'',first_name:'',last_name:'',email:'',course:'',year_level:''}
export default function MembersPage(){const [members,setMembers]=useState([]),[query,setQuery]=useState(''),[form,setForm]=useState(blank),[error,setError]=useState(''),[saving,setSaving]=useState(false)
async function load(){const {data,error}=await supabase.from('profiles').select('id,student_number,first_name,last_name,email,course,year_level,role,auth_user_id').order('created_at',{ascending:false});if(error)setError(error.message);else setMembers(data)}
useEffect(()=>{load()},[])
async function add(e){e.preventDefault();setError('');if(Object.values(form).some(v=>!String(v).trim()))return setError('All member fields are required.');setSaving(true);const {error}=await supabase.from('profiles').insert({...form,email:form.email.trim().toLowerCase(),year_level:Number(form.year_level),role:'MEMBER'});setSaving(false);if(error)setError(error.message);else{setForm(blank);load()}}
const filtered=members.filter(m=>`${m.student_number} ${m.first_name} ${m.last_name} ${m.email}`.toLowerCase().includes(query.toLowerCase()))
return <section className="mx-auto max-w-6xl px-5 py-12"><BackLink to="/admin">Back to dashboard</BackLink><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_2fr]"><form className="rounded-xl border bg-white p-6 shadow-sm space-y-3" onSubmit={add}><h1 className="text-2xl font-bold">Add member</h1>{error&&<p className="text-sm text-red-700">{error}</p>}{Object.entries(blank).map(([key])=><input className="w-full rounded-md border px-3 py-2" key={key} name={key} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={key.replace('_',' ')} type={key==='email'?'email':key==='year_level'?'number':'text'} value={form[key]}/>) }<button className="w-full rounded-md bg-indigo-700 py-2.5 font-semibold text-white" disabled={saving}>{saving?'Adding...':'Add member'}</button><Link className="block text-center text-sm font-medium text-indigo-700" to="/admin/members/import">Import CSV/XLSX</Link></form><div><h2 className="text-2xl font-bold">Members</h2><input className="mt-4 w-full rounded-md border px-3 py-2" onChange={e=>setQuery(e.target.value)} placeholder="Search members" value={query}/><div className="mt-4 overflow-x-auto rounded-xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Student</th><th className="p-3 text-left">Name</th><th className="p-3 text-left">Email</th><th className="p-3 text-left">Course</th><th className="p-3 text-left">Account</th></tr></thead><tbody>{filtered.map(m=><tr className="border-t" key={m.id}><td className="p-3">{m.student_number}</td><td className="p-3">{m.first_name} {m.last_name}</td><td className="p-3">{m.email}</td><td className="p-3">{m.course}</td><td className="p-3">{m.auth_user_id?'Linked':'Not registered'}</td></tr>)}</tbody></table></div></div></div></section>}
