import { useState } from 'react'
import * as XLSX from 'xlsx'
import BackLink from '../../components/BackLink.jsx'
import { supabase } from '../../services/supabase/client.js'
const required=['student_number','first_name','last_name','email','course','year_level']
export default function MemberImportPage(){const [valid,setValid]=useState([]),[invalid,setInvalid]=useState([]),[message,setMessage]=useState(''),[saving,setSaving]=useState(false)
async function choose(e){setMessage('');const file=e.target.files[0];if(!file)return;const book=XLSX.read(await file.arrayBuffer(),{type:'array'});const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:''}).map((row,i)=>({row:i+2,...Object.fromEntries(Object.entries(row).map(([k,v])=>[k.trim().toLowerCase(),String(v).trim()]))}));const seen=new Set();const {data=[]}=await supabase.from('profiles').select('student_number,email');const existing=new Set(data.flatMap(m=>[m.student_number,m.email.toLowerCase()]));const good=[],bad=[];rows.forEach(r=>{const miss=required.filter(k=>!r[k]);const duplicate=seen.has(r.student_number)||seen.has(r.email.toLowerCase())||existing.has(r.student_number)||existing.has(r.email.toLowerCase());if(miss.length||duplicate)bad.push({...r,reason:miss.length?`Missing: ${miss.join(', ')}`:'Duplicate student number or email'});else{seen.add(r.student_number);seen.add(r.email.toLowerCase());good.push({...r,email:r.email.toLowerCase(),year_level:Number(r.year_level)})}});setValid(good);setInvalid(bad)}
async function confirm(){setSaving(true);const {error}=await supabase.from('profiles').insert(valid.map(({row,...m})=>({...m,role:'MEMBER'})));setSaving(false);if(error)setMessage(error.message);else{setMessage(`${valid.length} members imported.`);setValid([])}}
return <section className="mx-auto max-w-5xl px-5 py-12"><BackLink to="/admin/members">Back to members</BackLink><h1 className="mt-6 text-3xl font-bold">Import members</h1><p className="mt-3 text-slate-600">Upload a .csv or .xlsx with: {required.join(', ')}.</p><input accept=".csv,.xlsx" className="mt-6" onChange={choose} type="file"/>{message&&<p className="mt-4 text-sm">{message}</p>}{(valid.length>0||invalid.length>0)&&<div className="mt-6 grid gap-6 md:grid-cols-2"><div className="rounded-xl border bg-white p-5"><h2 className="font-bold">Valid rows ({valid.length})</h2><p className="mt-2 text-sm text-slate-600">Only these rows will be inserted after confirmation.</p>{valid.slice(0,10).map(r=><p className="mt-2 text-sm" key={r.row}>{r.row}: {r.student_number} — {r.email}</p>)}{valid.length>0&&<button className="mt-5 rounded-md bg-indigo-700 px-4 py-2.5 font-semibold text-white" disabled={saving} onClick={confirm}>{saving?'Importing...':`Confirm import (${valid.length})`}</button>}</div><div className="rounded-xl border bg-white p-5"><h2 className="font-bold">Invalid or duplicate ({invalid.length})</h2>{invalid.slice(0,10).map(r=><p className="mt-2 text-sm text-red-700" key={r.row}>{r.row}: {r.reason}</p>)}</div></div>}</section>}
